// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mppgtefvuceeubyapjng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wcGd0ZWZ2dWNlZXVieWFwam5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMjY5NjIsImV4cCI6MjA1NzkwMjk2Mn0.WsMSPz8fzpH3iEzW3l8VDaqOjOih9AypN_m41DG-LmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);